#pragma once

#define SOCKET_OK 1
#define ERROR_INTERNAL -1
#define ERROR_INVALID_PARAM -2
#define ERROR_BUFFER_TOO_SMALL -3
#define ERROR_ALLOCATING_MEMORY -4
#define ERROR_CONNECTION -5
#define ERROR_TCP_RECV -6
#define ERROR_TCP_SEND -7
#define ERROR_UDP_RECV_FROM -8
#define ERROR_UDP_SEND_TO -9
#define ERROR_TCP_TIMEOUT -10
#define ERROR_TCP_WOULD_BLOCK -11